//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef ESP32CAN_H
#define ESP32CAN_H

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
#include <nanoPackStruct.h>

struct Library_ESP32CAN_ESP32CAN_CAN
{
    NANOCLR_NATIVE_DECLARE(InitNative___STATIC__VOID);

    //--//
};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_ESP32CAN;

#endif // ESP32CAN_H
