//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "ESP32CAN.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    Library_ESP32CAN_ESP32CAN_CAN::InitNative___STATIC__VOID,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_ESP32CAN =
{
    "ESP32CAN",
    0x7DF4AB11,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
